apiVersion: batch/v1
kind: Job
metadata:
  name: "mlflow-model"
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: "mlflow-model"
        image: "bangvo/mflow"
        command: ["python train.py --alpha {alpha} --l1-ratio {l1_ratio}"]
#         resources:
#           limits:
#             memory: 512Mi
#           requests:
#             memory: 256Mi
        restartPolicy: Never
